"""
app.py

Streamlit application for the LLMOps StudyBuddy project.

This app provides:
- A UI for selecting quiz settings (topic, type, difficulty, quantity)
- Interactive presentation of questions generated by the QuestionGenerator
- Submission, scoring, and visual feedback on quiz performance
- CSV export of results for later analysis

The UI works together with:
- QuestionGenerator     (LLM-driven question creation)
- QuizManager           (quiz state, evaluation, export)
- Streamlit session_state (UI lifecycle management)
"""

# --------------------------------------------------------------
# Imports
# --------------------------------------------------------------
import os

import streamlit as st
from dotenv import load_dotenv

# Quiz management + helpers
from src.utils.helpers import QuizManager, rerun

# LLM question-generation service
from src.generator.question_generator import QuestionGenerator

# Load environment variables
load_dotenv()


# --------------------------------------------------------------
# Main App
# --------------------------------------------------------------
def main() -> None:
    """
    Run the Streamlit StudyBuddy application.

    Manages session state, quiz setup, generation, evaluation,
    and result export.
    """

    # App configuration
    st.set_page_config(page_title="Study Buddy AI", page_icon="📚", layout="wide")

    # ----------------------------------------------------------
    # Session State Initialisation
    # ----------------------------------------------------------
    if "quiz_manager" not in st.session_state:
        st.session_state.quiz_manager = QuizManager()

    if "quiz_generated" not in st.session_state:
        st.session_state.quiz_generated = False

    if "quiz_submitted" not in st.session_state:
        st.session_state.quiz_submitted = False

    if "rerun_trigger" not in st.session_state:
        st.session_state.rerun_trigger = False

    # ----------------------------------------------------------
    # Layout: Sidebar (controls) + Main (quiz)
    # ----------------------------------------------------------
    sidebar, main_col = st.columns([1, 2])

    # ===========================
    # Sidebar — Quiz Configuration
    # ===========================
    with sidebar:
        st.title("🎛️ Quiz Settings")

        # -----------------------
        # Question type selector
        # -----------------------
        question_type = st.selectbox(
            "Select Question Type",
            ["Multiple Choice", "Fill in the Blank"],
            index=0,
        )

        # -----------------------
        # Topic selection
        # -----------------------
        st.markdown("### 🧠 Topic")

        topic_options = {
            "📜 History": "history, covering different periods, regions, and major events",
            "🌍 Geography": "world geography, including countries, capitals, landforms, and climate",
            "🧪 Science": "general science, including physics, chemistry, and basic scientific principles",
            "🧬 Biology": "biology, including cells, genetics, evolution, and ecosystems",
            "📐 Mathematics": "mathematics, including algebra, geometry, and basic calculus ideas",
            "💻 Computer Science": "computer science fundamentals, including algorithms and data structures",
            "📈 Economics": "economics, including microeconomics and macroeconomics concepts",
            "⚽ Sports": "general sports knowledge, including rules, famous events, and athletes",
            "📝 Custom topic": None,
        }

        topic_choice = st.selectbox(
            "Choose a topic",
            list(topic_options.keys()),
            index=0,
        )

        custom_topic = ""
        if topic_options[topic_choice] is None:
            custom_topic = st.text_input(
                "Or enter a custom topic",
                placeholder="e.g., Indian history, linear algebra, World War II",
            )

        # Build the effective topic string sent to the model
        if topic_options[topic_choice] is None:
            effective_topic = custom_topic.strip()
        else:
            effective_topic = topic_options[topic_choice]

        # -----------------------
        # Difficulty selector
        # -----------------------
        st.markdown("### 🎯 Difficulty")

        difficulty = st.selectbox(
            "Difficulty Level",
            ["Easy", "Medium", "Hard"],
            index=1,
        )

        # -----------------------
        # Number of questions
        # -----------------------
        st.markdown("### 🔢 Number of Questions")

        num_questions = st.number_input(
            "Number of Questions",
            min_value=1,
            max_value=10,
            value=5,
        )

        st.markdown("")

        # -----------------------
        # Generate Quiz Button
        # -----------------------
        if st.button("🚀 Generate Quiz", use_container_width=True):
            if not effective_topic:
                st.error("Please select a topic or enter a custom one before generating the quiz.")
            else:
                st.session_state.quiz_submitted = False

                generator = QuestionGenerator()

                success = st.session_state.quiz_manager.generate_questions(
                    generator,
                    effective_topic,
                    question_type,
                    difficulty,
                    num_questions,
                )

                st.session_state.quiz_generated = success
                rerun()

    # ===========================
    # Main Content — Quiz & Results
    # ===========================
    with main_col:
        # App Title
        st.title("📚 Study Buddy AI")

        # -----------------------
        # Quiz Display & Answer Input
        # -----------------------
        if st.session_state.quiz_generated and st.session_state.quiz_manager.questions:
            st.markdown("## 📝 Quiz")

            st.session_state.quiz_manager.attempt_quiz()

            if st.button("✅ Submit Quiz"):
                st.session_state.quiz_manager.evaluate_quiz()
                st.session_state.quiz_submitted = True
                rerun()

        # -----------------------
        # Quiz Results
        # -----------------------
        if st.session_state.quiz_submitted:
            st.markdown("## 📊 Quiz Results")

            results_df = st.session_state.quiz_manager.generate_result_dataframe()

            if not results_df.empty:
                # Calculate score
                correct_count = results_df["is_correct"].sum()
                total_questions = len(results_df)
                score_percentage = (correct_count / total_questions) * 100

                st.write(f"Overall score: **{score_percentage:.2f}%**")

                # Detailed per-question feedback
                for _, result in results_df.iterrows():
                    q_num = result["question_number"]

                    if result["is_correct"]:
                        st.success(f"✅ Question {q_num}: {result['question']}")
                    else:
                        st.error(f"❌ Question {q_num}: {result['question']}")
                        st.write(f"Your answer: `{result['user_answer']}`")
                        st.write(f"Correct answer: `{result['correct_answer']}`")

                    st.markdown(" ")

                # -------------------
                # Save Results
                # -------------------
                st.markdown("---")
                st.markdown("### 💾 Save Your Results")

                if st.button("💾 Save Results to CSV"):
                    saved_file = st.session_state.quiz_manager.save_to_csv()

                    if saved_file:
                        with open(saved_file, "rb") as f:
                            st.download_button(
                                label="⬇️ Download Results",
                                data=f.read(),
                                file_name=os.path.basename(saved_file),
                                mime="text/csv",
                            )
                    else:
                        st.warning("No results available.")


# --------------------------------------------------------------
# Entry Point
# --------------------------------------------------------------
if __name__ == "__main__":
    main()
